//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMP_CRUD_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_Emp_Oct_MVCEntities : DbContext
    {
        public DB_Emp_Oct_MVCEntities()
            : base("name=DB_Emp_Oct_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblDept> tblDepts { get; set; }
        public virtual DbSet<tblEmpDetail> tblEmpDetails { get; set; }
        public virtual DbSet<tblLogin> tblLogins { get; set; }
    }
}
